{{- if or (eq .Values.operator.watch.mode "multi") (eq .Values.operator.watch.mode "all")  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: activemq-artemis-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: activemq-artemis-operator-role
subjects:
- kind: ServiceAccount
  name: activemq-artemis-controller-manager
  namespace: {{ .Values.namespace.name }}
{{- end }}

