{{- if eq .Values.operator.watch.mode "single" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: activemq-artemis-operator-rolebinding
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: activemq-artemis-operator-role
subjects:
- kind: ServiceAccount
  name: activemq-artemis-controller-manager
{{- end }}

